### ctx.isSafeDomain(domain)
eggjs/security pull request #26
Opened 2018-01-20 11:36 UTC by codefine

Add wildcard character(`*`) rule to `ctx.isSafeDomain`.

---

The `config.security.domainWhileList` can node like blow:
``` javascript
config.security = {
    domainWhiteList: [
        'http://192.168.1.100:8080', // normal string rule
        '192.168.1.*', // will transfer to RegExp rule
        '192.168.2.100:*', // will transfer to RegExp rule
        '*.somesite.com' // will transfer to RegExp rule
    ]
};
```

It helps greatly with client-server-separation development when using egg.

2018-01-20 15:16 UTC, dead-horse commented
use wildcard library like https://github.com/sindresorhus/matcher

2018-01-20 15:25 UTC, codefine commented
@dead-horse 源文件使用endsWith来判断，这个模块需要植入到源文件中吧？

2018-02-24 06:39 UTC, atian25 commented
ping @jtyjty99999

2018-02-24 09:02 UTC, dead-horse commented
判断一下如果包含 wildcard 字符就用 wildcard 的库来处理，否则就沿用原来的 endsWith 好了

2018-03-05 05:45 UTC, popomore requested changes
使用 https://github.com/sindresorhus/matcher

2018-08-08 06:51 UTC, Maledong commented
@dead-horse：This has been merged and fixed. So close this :)

2018-08-09 08:06 UTC, atian25 commented
@Maledong this feature is landed ? which PR?

2018-08-10 06:53 UTC, Maledong commented
@atian25: https://github.com/eggjs/egg-security/pull/42

2018-08-14 03:03 UTC, closed without merging