[WIP]feat: add refererpolicy support
eggjs/security pull request #27
Opened 2018-03-09 09:18 UTC by jtyjty99999

https://github.com/eggjs/egg/issues/2179

2018-03-09 09:50 UTC, fengmk2 requested changes

2018-03-09 09:50 UTC, fengmk2 commented on config/config.default.js
> +    refererpolicy: {
大小写问题

2018-03-09 09:51 UTC, atian25 commented on config/config.default.js
> +    refererpolicy: {
记得有一个提醒的地方，也要加吧

2018-03-09 14:16 UTC, jtyjty99999 commented
@fengmk2  修改了

2018-03-10 08:34 UTC, fengmk2 commented
参考 https://github.com/krakenjs/lusca/commit/d3bb1b ，默认开启为 same-origin？这个似乎对现在没有任何风险。

2018-03-10 08:35 UTC, fengmk2 commented
哦，它也是默认关闭。。

2018-03-10 08:38 UTC, fengmk2 commented on config/config.default.js
> +      enable: false,
加个 `value: ''` 默认值

2018-03-10 08:38 UTC, fengmk2 commented on lib/middlewares/referrerPolicy.js
> +    const policy = opts.value || 'no-referrer';
value 的默认值在 config 里面设置吧，为空就直接跳过

2018-03-10 08:39 UTC, fengmk2 commented on lib/middlewares/referrerPolicy.js
> +    if (ALLOWED_POLICIES_ENUM.indexOf(policy) === -1) {
使用 obj hash 判断吧，比较快，不需要遍历一次 ALLOWED_POLICIES_ENUM

2018-03-14 07:07 UTC, jtyjty99999 commented
@fengmk2 已经修改，默认策略我改成了  no-referrer-when-downgrade 不开启， https协议降级到http协议时不发送referrer，感觉这样是最合适的  https://github.com/TryGhost/Ghost/issues/7235  这个issue也是这个观点。

2018-03-14 07:08 UTC, fengmk2 approved these changes

2018-03-14 07:14 UTC, jtyjty99999 commented
https://github.com/h5bp/server-configs-apache/pull/130/files h5bp中apache的默认配置也是这个

2018-03-14 08:15 UTC, merged

2018-03-14 08:15 UTC, fengmk2 commented
2.1.0