fix: shtml check domainWhiteList hostname get null
eggjs/security pull request #49
Opened 2018-11-14 08:28 UTC by EliYao

like `<a href="javascript:;">test</a> `this url check hostname will get null and meet TypeError: Cannot read property 'toLocaleLowerCase' of null error。

So, add check hostname is null and remove toLowerCase，because in isSafeDomain function have use toLowerCase method to domain。

2018-11-14 09:42 UTC, atian25 commented
`<a href="javascript:;">test</a>` should stop send request such as `<a href="javascript:void();return false;">test</a>`

2018-11-14 14:04 UTC, jtyjty99999 requested changes
get
need a test case

2018-11-15 01:13 UTC, atian25 approved these changes

2018-11-15 01:13 UTC, atian25 commented
@jtyjty99999 check again

2018-11-15 02:57 UTC, jtyjty99999 approved these changes

2018-11-15 02:57 UTC, merged

2018-11-15 02:58 UTC, jtyjty99999 commented
点的好快。。你发版本？

2018-11-15 02:58 UTC, atian25 commented
好

2018-11-15 02:59 UTC, atian25 commented
2.4.1 @EliYao

2018-11-15 03:36 UTC, EliYao commented
赞